<!DOCTYPE html>
<html>
    <head>

        <!--force IE into compatibility -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <title>ROFLvid</title>
        <?php print $headerInclude; ?>
    </head>
    <body>

        <div id="header">
            <div id="header_wrapper">
                <?php print $navigation; ?>
            </div>
        </div>
        <div id="main">
            <div id="info-content"> 
                <h1>Terms of Services</h1>
                
                <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                    <li dir="ltr" style="list-style-type: decimal; font-size: 15px; font-family: Arial; vertical-align: baseline; margin-left: 24px;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Introduction and Acceptance</span></b></li>
                </ol>
                <p dir="ltr" style="margin-left: 18pt; margin-top: 0pt; margin-bottom: 0pt;">
                    <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Welcome to the website of ROFLvid, (hereinafter, &quot;us&quot;, &quot;we&quot;, or &quot;ROFLvid&quot;). These Terms of Service apply solely to the ROFLvid website.</span></b></p>
                <p dir="ltr" style="margin-left: 18pt; margin-top: 0pt; margin-bottom: 0pt;">
                    <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">PLEASE READ THESE TERMS OF SERVICE CAREFULLY BEFORE USING THE ROFLVID WEBSITE. BY ACCESSING AND/OR USING THIS ROFLVID WEBSITE YOU ARE AGREEING TO COMPLY WITH THESE TERMS OF SERVICE, WHICH MAY CHANGE FROM TIME TO TIME. IF YOU DO NOT AGREE TO BE BOUND BY THESE TERMS OF SERVICE, DO NOT ACCESS OR USE THIS ROFLVID WEBSITE.</span></b></p>
                <p dir="ltr" style="margin-left: 18pt; margin-top: 0pt; margin-bottom: 0pt;">
                    <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">You agree that these Terms of Service are supported by good and valuable consideration. Such consideration includes, without limitation, your use of the ROFLvid Website and the materials and information available on the same.</span></b></p>
                <p dir="ltr" style="margin-left: 18pt; margin-top: 0pt; margin-bottom: 0pt;">
                    <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">In addition to these Terms of Service, ROFLvid has established a Privacy Policy to explain how user information is collected and used by ROFLvid.</span><span style="font-size: 15px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">It is incorporated by reference into these Terms of Service. By accessing or using the Website, you are signifying your acknowledgement and agreement to ROFLvid&#39;s Privacy Policy.</span></b></p>
                <br />
                <ol start="2" style="margin-top: 0pt; margin-bottom: 0pt;">
                    <li dir="ltr" style="list-style-type: decimal; font-size: 15px; font-family: Arial; vertical-align: baseline; margin-left: 24px;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Service</span></b>
                        <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">The Terms of Service apply to all users of ROFLvid, including users that will be contributors of content on the Website. &ldquo;Content&rdquo; includes the sounds, music, videos, audiovisual combinations, text, software, scripts, graphics, photos you may view on, access or contribute through ROFLvid. This service includes all aspects of ROFLvid, including but not limited to all products, software and services offered through the ROFLvid website.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Service may contain links to third party websites that are not controlled or owned by ROFLvid. ROFLvid has no control over and assumes no responsibility for the privacy policies, content or practices of third party websites. ROFLvid will not censor or edit the content of any third party site. By using any ROFLvid website, you relieve ROFLvid from all liability that may arise from the use of any third party website.</span></b></li>
                        </ol>
                    </li>
                    <li dir="ltr" style="list-style-type: decimal; font-size: 15px; font-family: Arial; vertical-align: baseline; margin-left: 24px;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">ROFLvid Website Access and Use</span></b>
                        <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">When accessing our Website, including without limitation to the Website Content, you agree to comply with all applicable federal, provincial, state and local laws including, without limitation copyright law. Except as expressly permitted in these Terms of Service, you may not use, reproduce, distribute, publicly display, publicly perform, publish, transmit, or otherwise exploit Website Content for any purpose whatsoever without obtaining prior written consent from us or, in the case of third-party content, its respective owner. </span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">In order to access some features of ROFLvid, you will have to create a ROFLvid account. You may never use another account without permission. When creating a user account, you must provide accurate and complete information and you will be solely responsible for the activity that occurs on your account. You must notify ROFLvid immediately of any security breach or unauthorized use of your account. You will also be liable for the losses of ROFLvid or others due to unauthorised use of your account.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Furthermore, except as expressly permitted in these Terms of Service, you may not:</span></b>
                                <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">remove, alter, cover, or distort any copyright, trademark, or other proprietary rights notice on this Website;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">circumvent, disable or otherwise interfere with security-related features of our Website including, without limitation, any features that prevent or restrict use or copying of any content or enforce limitations on the use of our Website or Website Content;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">use an automatic device (such as a robot or spider) or manual process to copy or &quot;scrape&quot; our Website or Website Content for any purpose without the express written permission of ROFLvid. Notwithstanding the foregoing, ROFLvid grants public search engine operators permission to use automatic devices (such as robots or spiders) to copy Website Content from our Website for the sole purpose of creating (and only to the extent necessary to create) a searchable index of Website Content that is available to the public. ROFLvid reserves the right to revoke this permission (generally or specifically) at any time;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">collect or harvest any personally identifiable information from our Website including, without limitation, user names, passwords, email addresses;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">solicit other users to join or become members of any commercial online service or other organization without our prior written approval;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">attempt to or interfere with the proper working of our Website or impair, overburden, or disable the same;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">decompile, reverse engineer, or disassemble any portion of any our Website;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">use network-monitoring software to determine architecture of or extract usage data from any of our Website;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">encourage conduct that violates any local, state or federal law, either civil or criminal, or impersonate another user, person, or entity (e.g., using another person&#39;s Membership (as defined in Section B) without permission, etc.);</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">engage in any conduct that restricts or inhibits any other user from using or enjoying our Website.</span></b></li>
                                </ol>
                            </li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">You agree to cooperate fully with ROFLvid to investigate any suspected or actual activity that is in breach of these Terms of Service.</span></b></li>
                        </ol>
                    </li>
                </ol>
                <br />
                <ol start="4" style="margin-top: 0pt; margin-bottom: 0pt;">
                    <li dir="ltr" style="list-style-type: decimal; font-size: 15px; font-family: Arial; vertical-align: baseline; margin-left: 24px;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">User Content</span></b>
                        <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">We permit users to post, upload, transmit through, or otherwise make available on our Website (collectively, &quot;submit&quot;) messages, templates, text, illustrations, files, images, graphics, photos, comments, sounds, music, videos, information, content, and/or other materials (&quot;User Content&quot;). Subject to the rights and license you grant herein, you retain all right, title and interest in your User Content. We do not guarantee any confidentiality with respect to User Content even if it is not published on our Website. It is solely your responsibility to monitor and protect any intellectual property rights that you may have in your User Content, and we do not accept any responsibility for the same.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">You shall not submit any User Content protected by copyright, trademark, patent, trade secret, moral right, or other intellectual property or proprietary right without the express permission of the owner of the respective right. You are solely liable for any damage resulting from your failure to obtain such permission or from any other harm resulting from User Content that you submit.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">You represent, warrant, and covenant that you will not submit any User Content that:</span></b>
                                <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">violates or infringes in any way upon the rights of others, including, but not limited to, any copyright, trademark, patent, trade secret, moral right, or other intellectual property or proprietary right of any person or entity;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">impersonates another or is unlawful, threatening, abusive, libelous, defamatory, invasive of privacy or publicity rights, vulgar, obscene, profane, pornographic, or otherwise objectionable;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">encourages conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any law;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">is an advertisement for goods or services or a solicitation of funds;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">includes personal information such as messages which identify phone numbers, social security numbers, account numbers, addresses, or employer references;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">contains a formula, instruction, or advice that could cause harm or injury; or</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">is a chain letter of any kind.</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">in our sole discretion restricts or inhibits any other user from using or enjoying our Website will not be permitted.</span></b></li>
                                </ol>
                            </li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">By submitting User Content to us, you automatically grant, or warrant that the owner has expressly granted, to us a worldwide, royalty-free, perpetual, irrevocable, non-exclusive, and transferable right and license to use, reproduce, distribute, create derivative works based upon (including, without limitation, translations), publicly display, publicly perform, transmit, and publish the User Content (in whole or in part) as we, in our sole discretion, deem appropriate including, without limitation, </span></b>
                                <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">in connection with our business;</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">in connection with the businesses of our successors, parents, subsidiaries, and their related companies.</span></b></li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                </ol>
                <p dir="ltr" style="margin-left: 54pt; margin-top: 0pt; margin-bottom: 0pt;">
                    <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">We may exercise this grant in any format, media or technology now known or later developed for the full term of any copyright that may exist in such User Content. Furthermore, you also grant other users permission to access your User Content and to use, reproduce, distribute, create derivative works based upon, publicly display, publicly perform, transmit, and publish your User Content for personal, non-commercial use as permitted by the functionality of any of our Website and these </span><span style="font-size: 15px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Terms of Service</span><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">.</span></b></p>
                <br />
                <ol start="5" style="margin-top: 0pt; margin-bottom: 0pt;">
                    <li>
                        <ol start="5" style="margin-top: 0pt; margin-bottom: 0pt;">
                            <li dir="ltr" style="list-style-type: lower-alpha; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">We reserve the right to display advertisements in connection with your User Content and to use your User Content for advertising and promotional purposes. You acknowledge and agree that your User Content may be included on the Website and advertising networks of our distribution partners and third-party service providers (including their downstream users).</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">We have the right, but not the obligation, to monitor User Content. We have the right in our sole discretion and for any reason whatsoever to edit, refuse to post, remove, or disable access to any User Content.</span></b></li>
                        </ol>
                    </li>
                    <li dir="ltr" style="list-style-type: decimal; font-size: 15px; font-family: Arial; vertical-align: baseline; margin-left: 24px;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Website Content &amp; Third Party Links</span></b>
                        <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">We provide our Website and Website Content, for the entertainment and promotional purposes of providing a fun and interactive platform for watching videos. You may not rely on any information and opinions expressed on any of our Website for any other purpose. In all instances, it is your responsibility to evaluate the accuracy, timeliness, completeness, or usefulness of Website Content. Under no circumstances will we be liable for any loss or damage caused by your reliance on any Website Content.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">In many instances, Website Content will include content posted by a third-party or will represent the opinions and judgments of a third-party. We do not endorse, warrant and are not responsible for the accuracy, timeliness, completeness, or reliability of any opinion, advice, or statement made on our Website by anyone other than authorized employees or spokespersons while acting in their official capacities.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">If there is a dispute between persons accessing our Website or between persons accessing our Website and any third party, you understand and agree that we are under no obligation to become involved. If there is such a dispute, you hereby release ROFLvid and its officers, directors, employees, parents, partners, successors, agents, affiliates, subsidiaries, and their related companies from claims, demands, and damages of every kind or nature arising out of, relating to, or in any way connected with such dispute.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Our Website may contain links to other Website maintained by third parties. We do not operate or control, in any respect, or necessarily endorse the content found on these third-party Website. You assume sole responsibility for your use of third-party links. We are not responsible for any content posted on third-party Website or liable to you for any loss or damage of any sort incurred as a result of your dealings with any third-party or their website.</span></b></li>
                        </ol>
                    </li>
                    <li dir="ltr" style="list-style-type: decimal; font-size: 15px; font-family: Arial; vertical-align: baseline; margin-left: 24px;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Indemnification</span></b></li>
                </ol>
                <p dir="ltr" style="margin-left: 18pt; margin-top: 0pt; margin-bottom: 0pt;">
                    <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">You agree to indemnify and hold harmless ROFLvid and its officers, directors, employees, parents, partners, successors, agents, distribution partners, affiliates, subsidiaries, and their related companies from and against any and all claims, liabilities, losses, damages, obligations, costs and expenses (including reasonable attorneys&rsquo; fees and costs) arising out of, related to, or that may arise in connection with: </span></b></p>
                <br />
                <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                    <li dir="ltr" style="list-style-type: lower-roman; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">your access to or use of any of our Website;</span></b></li>
                    <li dir="ltr" style="list-style-type: lower-roman; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">User Content provided by you or through use of your Membership; </span></b></li>
                    <li dir="ltr" style="list-style-type: lower-roman; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">any actual or alleged violation or breach by you of these Terms of Service;</span></b></li>
                    <li dir="ltr" style="list-style-type: lower-roman; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">any actual or alleged breach of any representation, warranty, or covenant that you have made to us; or your acts or omissions. You agree to cooperate fully with us in the defense of any claim that is the subject of your obligations hereunder.</span></b></li>
                </ol>
                <br />
                <ol start="7" style="margin-top: 0pt; margin-bottom: 0pt;">
                    <li dir="ltr" style="list-style-type: decimal; font-size: 15px; font-family: Arial; vertical-align: baseline; margin-left: 24px;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Disclaimers</span></b></li>
                </ol>
                <p dir="ltr" style="margin-left: 18pt; margin-top: 0pt; margin-bottom: 0pt;">
                    <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">YOU EXPRESSLY AGREE THAT USE OF OUR WEBSITE IS AT YOUR SOLE RISK. OUR WEBSITE AND WEBSITE CONTENT ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. WITHOUT LIMITING THE FOREGOING AND TO THE FULLEST EXTENT PERMITTED BY LAW, ROFLVID AND ITS OFFICERS, DIRECTORS, EMPLOYEES, PARENTS, PARTNERS, SUCCESSORS, AGENTS, DISTRIBUTION PARTNERS, AFFILIATES, SUBSIDIARIES, AND THEIR RELATED COMPANIES DISCLAIM ANY AND ALL WARRANTIES INCLUDING ANY: </span></b></p>
                <br />
                <ol start="5" style="margin-top: 0pt; margin-bottom: 0pt;">
                    <li dir="ltr" style="list-style-type: lower-roman; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">WARRANTIES THAT THE WEBSITE WILL MEET YOUR REQUIREMENTS;</span></b></li>
                    <li dir="ltr" style="list-style-type: lower-roman; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">WARRANTIES CONCERNING THE AVAILABILITY, ACCURACY, SECURITY, USEFULNESS, TIMELINESS, OR INFORMATIONAL CONTENT OF THE ROFLVID WEBSITE OR WEBSITE CONTENT;</span></b></li>
                    <li dir="ltr" style="list-style-type: lower-roman; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE;</span></b></li>
                    <li dir="ltr" style="list-style-type: lower-roman; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">WARRANTIES FOR SERVICES OR GOODS RECEIVED THROUGH OR ADVERTISED ON OUR WEBSITE OR ACCESSED THROUGH ANY OF OUR WEBSITE;</span></b></li>
                    <li dir="ltr" style="list-style-type: lower-roman; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">WARRANTIES CONCERNING THE ACCURACY OR RELIABILITY OF THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE WEBSITE;</span></b></li>
                    <li dir="ltr" style="list-style-type: lower-roman; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">WARRANTIES THAT YOUR USE OF THE WEBSITE WILL BE SECURE OR UNINTERRUPTED; </span></b></li>
                    <li dir="ltr" style="list-style-type: lower-roman; font-size: 15px; font-family: Arial; vertical-align: baseline;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">WARRANTIES THAT ERRORS IN THE SOFTWARE WILL BE CORRECTED.</span></b></li>
                </ol>
                <br />
                <ol start="8" style="margin-top: 0pt; margin-bottom: 0pt;">
                    <li dir="ltr" style="list-style-type: decimal; font-size: 15px; font-family: Arial; vertical-align: baseline; margin-left: 24px;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Limitation on Liability</span></b>
                        <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">UNDER NO CIRCUMSTANCES SHALL ROFLVID OR ITS OFFICERS, DIRECTORS, EMPLOYEES, PARENTS, PARTNERS, SUCCESSORS, AGENTS, DISTRIBUTION PARTNERS, AFFILIATES, SUBSIDIARIES, OR THEIR RELATED COMPANIES BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES (EVEN IF ROFLVID HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), ARISING OUT OF, RELATING TO, OR IN ANY WAY CONNECTED WITH OUR WEBSITE OR THESE </span><span style="font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">TERMS OF SERVICE</span><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">. YOUR SOLE REMEDY FOR DISSATISFACTION WITH OUR WEBSITE INCLUDING, WITHOUT LIMITATION, THE WEBSITE CONTENT IS TO STOP USING OUR WEBSITE. SUCH LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF SERVICES OR PRODUCTS RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH ANY OF OUR WEBSITE OR ANY LINKS ON OUR WEBSITE, AS WELL AS BY REASON OF ANY INFORMATION OR ADVICE RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH ANY OF OUR WEBSITE OR ANY LINKS ON OUR WEBSITE. SUCH LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF ANY CONTENT POSTED BY A THIRD-PARTY OR CONDUCT OF A THIRD-PARTY ON OUR WEBSITE.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, IN NO EVENT SHALL THE CUMULATIVE LIABILITY OF ROFLVID AND ITS OFFICERS, DIRECTORS, EMPLOYEES, PARENTS, PARTNERS, SUCCESSORS, AGENTS, DISTRIBUTION PARTNERS, AFFILIATES, SUBSIDIARIES, AND THEIR RELATED COMPANIES EXCEED THE GREATER OF THE TOTAL PAYMENTS RECEIVED FROM YOU BY ROFLVID DURING THE PRECEDING TWELVE (12) MONTH PERIOD OR $100. FURTHERMORE, YOU AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF, RELATING TO, OR IN ANY WAY CONNECTED WITH ANY OF OUR WEBSITE OR THESE </span><span style="font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">TERMS OF SERVICE</span><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;"> MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES; OTHERWISE, SUCH CAUSE OF ACTION SHALL BE PERMANENTLY BARRED.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">In some jurisdictions limitations of liability are not permitted. In such jurisdictions, some of the foregoing limitations may not apply to you. These limitations shall apply to the fullest extent permitted by law</span><span style="font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">.</span></b></li>
                        </ol>
                    </li>
                    <li dir="ltr" style="list-style-type: decimal; font-size: 15px; font-family: Arial; vertical-align: baseline; margin-left: 24px;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Termination</span></b>
                        <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">We reserve the right in our sole discretion and at any time to terminate or suspend your Membership and/or block your access to our Website for any reason including, without limitation if you have failed to comply with the letter and spirit of these Terms of Service. You agree that ROFLvid shall not be liable to you or any third party for any termination or suspension of your Membership or for blocking your access to our Website.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">If you become a registered user, you may terminate your Membership at any time by going to the Options &nbsp;page and selecting the appropriate option.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Any suspension or termination shall not affect your obligations to us under these Terms of Service. The provisions of these Terms of Service which by their nature should survive the suspension or termination of your Membership or these Terms of Service shall survive including, but not limited to the rights and licenses that you have granted hereunder, indemnities, releases, disclaimers, limitations on liability, provisions related to choice of law, dispute resolution, no class action, no trial by jury and all of the miscellaneous provisions in Section 17.</span></b></li>
                        </ol>
                    </li>
                    <li dir="ltr" style="list-style-type: decimal; font-size: 15px; font-family: Arial; vertical-align: baseline; margin-left: 24px;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Copyright Policy</span></b>
                        <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">ROFLvid respects the intellectual property rights of others and expects its users to do the same. In appropriate circumstances and at its sole discretion, ROFLvid may terminate and/or disable the Membership of users who it suspects to be infringers of the copyrights (or other intellectual property rights) of others. Additionally, in appropriate circumstances and in its sole discretion, ROFLvid may remove or disable access to material on any of its Website or hosted on its systems that may be infringing or the subject of infringing activity.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">If you are a copyright owner (or authorized to act on behalf of the copyright owner) and believe that your work&#39;s copyright has been infringed, please report your notice of infringement to us by providing our Designated Agent with a written notification of claimed infringement that includes substantially the following:</span></b>
                                <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site.</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material.</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Information reasonably sufficient to permit us to contact you, such as an address, telephone number, and, if available, an electronic mail address at which you may be contacted.</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</span></b></li>
                                    <li dir="ltr" style="list-style-type: lower-roman; vertical-align: baseline;">
                                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">We will investigate notices of copyright infringement and take appropriate actions under the DMCA. Inquiries that do not follow this procedure may not receive a response.</span></b></li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                    <li dir="ltr" style="list-style-type: decimal; font-size: 15px; font-family: Arial; vertical-align: baseline; margin-left: 24px;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Miscellaneous</span></b>
                        <ol style="margin-top: 0pt; margin-bottom: 0pt;">
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline; margin-left: 24px;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">No waiver by either party of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. The section headings used herein are for convenience only and shall not be given any legal import. If any provision of these </span><span style="font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Terms of Service</span><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;"> is held to be invalid or unenforceable, the invalidity of such provision shall not affect the validity of the remaining provisions of the </span><span style="font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Terms of Service</span><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">, which shall remain in full force and effect.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline; margin-left: 24px;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">These </span><span style="font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Terms of Service</span><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;"> (including the Privacy Policy and any Additional Terms incorporated by reference) constitute the entire agreement of the parties with respect to the subject matter hereof, and supersede all previous written or oral agreements between us with respect to such subject matter.</span></b></li>
                            <li dir="ltr" style="list-style-type: lower-alpha; vertical-align: baseline; margin-left: 24px;">
                                <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">You may not assign these </span><span style="font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Terms of Service</span><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;"> or assign any rights or delegate any obligations hereunder, in whole or in part, without our prior written consent. Any such purported assignment or delegation by you without the appropriate prior written consent will be null and void and of no force and effect. ROFLvid may assign these </span><span style="font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Terms of Service</span><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;"> or any rights hereunder without your consent and without notice.</span></b></li>
                        </ol>
                    </li>
                    <li dir="ltr" style="list-style-type: decimal; font-size: 15px; font-family: Arial; vertical-align: baseline; margin-left: 24px;">
                        <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">Notices</span></b></li>
                </ol>
                <p dir="ltr" style="margin-left: 18pt; margin-top: 0pt; margin-bottom: 0pt;">
                    <b id="internal-source-marker_0.984526589512825" style="font-weight: normal;"><span style="font-size: 16px; font-family: 'Segoe UI Light'; vertical-align: baseline; white-space: pre-wrap;">All notices, requests, and communications hereunder shall be in writing, and any such notice, request or other communication shall be deemed to have been given or made when delivered by hand.</span></b></p>
            </div>
            <?php print $footer; ?>
        </div>
        <!--Corner system-->
        <div id="facebook-dropzone"></div>

        <div id="pageslide"></div>
        <div id="activation-left-slide"></div>
    </body>
</html>